before:
  hooks:
    - go mod tidy
    - go generate
builds:
  - id: lure
    env:
      - CGO_ENABLED=0
    binary: lure
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - riscv64
archives:
  - replacements:
      386: i386
      amd64: x86_64
      arm64: aarch64
    files:
      - scripts/completion/*
nfpms:
  - id: lure
    package_name: linux-user-repository
    file_name_template: '{{.PackageName}}-{{.Version}}-{{.Os}}-{{.Arch}}'
    description: "Linux User REpository"
    replacements:
      386: i386
      amd64: x86_64
      arm64: aarch64
    homepage: 'https://gitea.arsenm.dev/Arsen6331/lure'
    maintainer: 'Arsen Musayelyan <arsen@arsenm.dev>'
    license: GPLv3
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    provides:
      - lure
    conflicts:
      - lure
    contents:
      - src: scripts/completion/bash
        dst: /usr/share/bash-completion/completions/lure
      - src: scripts/completion/zsh
        dst: /usr/share/zsh/site-functions/_lure
aurs:
  - name: linux-user-repository-bin
    homepage: 'https://gitea.arsenm.dev/Arsen6331/lure'
    description: "Linux User REpository"
    maintainers:
      - 'Arsen Musayelyan <arsen@arsenm.dev>'
    license: GPLv3
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/lure-bin.git'
    provides:
      - lure
    conflicts:
      - lure
    depends:
      - sudo
      - pacman
    package: |-
      # binaries
      install -Dm755 ./lure "${pkgdir}/usr/bin/lure"

      # completions
      install -Dm755 ./scripts/completion/bash ${pkgdir}/usr/share/bash-completion/completions/lure
      install -Dm755 ./scripts/completion/zsh ${pkgdir}/usr/share/zsh/site-functions/_lure
release:
  gitea:
    owner: Arsen6331
    name: lure
gitea_urls:
  api: 'https://gitea.arsenm.dev/api/v1/'
  download: 'https://gitea.arsenm.dev'
  skip_tls_verify: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc